### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by bobmyhill** [bobmyhill/pymuparser#1]
This checklist should be completed for every release of pymuparser

- [ ] Check new version can be used non-locally (`python -m pip install .`, then run from another directory)
- [ ] Open zenodo (dx.doi.org/10.5281/zenodo.11479574), start new version, reserve DOI (currently at the top of Basic Information)
- [ ] New branch (burnman-Major.Minor)
- [ ] Bump version number in new branch (in pyproject.toml)
- [ ] Update changelog.txt with major changes since the last release.
- [ ] Update pyproject.toml (if necessary, probably only Python versions need checking (as we've checked the installation works above)
- [ ] Update new badge link to zenodo (using the new reserved DOI) in Readme.md
- [ ] Push new branch to Github upstream pymuparser-Major.Minor (*not* main)
- [ ] Make release on Github using upstream pymuparser-Major.Minor branch
- [ ] Download zip file
- [ ] Upload new zip file to zenodo, fill in details on website (including new link to ReadTheDocs and github version)
- [ ] Save and publish in zenodo
- [ ] Check that the Github workflow has pushed the release to Pypi
- [ ] Merge upstream pymuparser-Major.Minor branch to main
- [ ] Bump version numbers in pyproject.toml on upstream main to `[Major].[Minor+1].0a0`
